### ISSUE TITLE
When i try to move dobot it gives me an output

### ISSUE THREAD

**Issue by Giulio2002** [luismesas/pydobot#6]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/pydobot/dobot.py", line 52, in run
    self._get_pose()
  File "/usr/local/lib/python2.7/dist-packages/pydobot/dobot.py", line 89, in _get_pose
    response = self._send_command(msg)
  File "/usr/local/lib/python2.7/dist-packages/pydobot/dobot.py", line 65, in _send_command
    self._send_message(msg)
  File "/usr/local/lib/python2.7/dist-packages/pydobot/dobot.py", line 74, in _send_message
    self.ser.write(msg.bytes())
  File "/usr/local/lib/python2.7/dist-packages/pydobot/message.py", line 36, in bytes
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pydobot/message.py", line 29, in refresh
    self.checksum = self.checksum + int(self.params[i])
ValueError: invalid literal for int() with base 10: '['
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/pydobot/dobot.py", line 52, in run
    self._get_pose()
  File "/usr/local/lib/python2.7/dist-packages/pydobot/dobot.py", line 89, in _get_pose
    response = self._send_command(msg)
  File "/usr/local/lib/python2.7/dist-packages/pydobot/dobot.py", line 65, in _send_command
    self._send_message(msg)
  File "/usr/local/lib/python2.7/dist-packages/pydobot/dobot.py", line 74, in _send_message
    self.ser.write(msg.bytes())
  File "/usr/local/lib/python2.7/dist-packages/pydobot/message.py", line 36, in bytes
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pydobot/message.py", line 29, in refresh
    self.checksum += self.params[i]
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

**Comment by morrisonj** [comment]
Off the top of my head I think this relates to you using Python 2.7. Try Python 3.x.

**Comment by Giulio2002** [comment]
I will

**Comment by Giulio2002** [comment]
Thanks
